stages:
  - install
  - build
  - test
  - build_docker

Npm ci:
  stage: install
  image: node:18
  script: 
    - cd frontend
    - npm ci
  cache:
    policy: push
    key: $CI_COMMIT_REF_SLUG
    paths:
      - "frontend/node_modules"

Build:
  stage: build
  image: node:18
  script: 
    - cd frontend
    - npm run build
  cache:
    policy: pull
    key: $CI_COMMIT_REF_SLUG
    paths:
      - "frontend/node_modules"

Test:
  stage: test
  image: node:18
  script: 
    - cd frontend
    - npm run test
  cache:
    policy: pull
    key: $CI_COMMIT_REF_SLUG
    paths:
      - "frontend/node_modules"  

Build docker:
  stage: build_docker
  service: 
    - docker:dind
  image: docker
  variables: 
    IMAGE_NAME: alexeistel/result-frontend
  only: 
    -master  
  script:
    - docker login -u alexeistel@gmail.com -p ${DOCKER_PWD}
    - docker build -f frontend.Dockerfile -t ${IMAGE_NAME} .
    - docker push ${IMAGE_NAME}

  
