services:
  date:
    image: alexeistel/result-date
    build:
      dockerfile: date.dockerfile
  result:
    image: alexeistel/result
    build: .
    ports: 
    - "3000:3000"
    env_file:
      - .env
    depends_on:
      - date